name: ve_news
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  audio_video_progress_bar: ^1.0.1
  connectivity_plus: ^4.0.1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  fpdart: ^0.6.0
  get_it: ^7.6.0
  google_fonts: ^5.0.0
  injectable: ^2.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  meta: ^1.9.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  uuid: ^3.0.7
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2

  flutter_bloc: ^8.1.3
  go_router: ^9.0.3
  projectile:
    path: ../../libs/projectile
  collection: ^1.17.1
  intl: ^0.18.1
  

dev_dependencies:
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sources/

